/*
  # Insert Sample Artworks Data

  1. Sample artworks with BB- prefixed IDs
  2. Maintains existing artwork structure
  3. Proper stock counts and pricing
*/

-- Insert sample artworks
INSERT INTO artworks (
  id, title, description, price, medium, category, style, dimensions, images, 
  in_stock, stock_count, featured, tags, date_created
) VALUES 
(
  'bb-001'::uuid,
  'BB-01 Sunset Meadow',
  'A vibrant fabric painting capturing the golden hour in a meadow filled with wildflowers. This piece uses mixed textiles to create depth and texture.',
  1850,
  'fabric',
  'Landscape',
  'Contemporary',
  '{"width": 40, "height": 30, "unit": "cm"}',
  ARRAY['https://images.pexels.com/photos/1568607/pexels-photo-1568607.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
  true,
  1,
  true,
  ARRAY['landscape', 'sunset', 'meadow', 'textiles'],
  '2024-01-15'::timestamptz
),
(
  'bb-002'::uuid,
  'BB-02 Abstract Dreams',
  'An expressive oil painting featuring bold brushstrokes and vibrant colors that evoke emotion and movement.',
  2800,
  'oil',
  'Abstract',
  'Modern',
  '{"width": 50, "height": 40, "unit": "cm"}',
  ARRAY['https://images.pexels.com/photos/1570264/pexels-photo-1570264.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
  true,
  1,
  true,
  ARRAY['abstract', 'colorful', 'modern', 'expressive'],
  '2024-02-10'::timestamptz
),
(
  'bb-003'::uuid,
  'BB-03 Ocean Waves',
  'A serene fabric painting depicting rolling ocean waves with intricate beadwork and embroidery details.',
  2150,
  'fabric',
  'Seascape',
  'Traditional',
  '{"width": 35, "height": 45, "unit": "cm"}',
  ARRAY['https://images.pexels.com/photos/1269968/pexels-photo-1269968.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
  false,
  0,
  false,
  ARRAY['ocean', 'waves', 'blue', 'beadwork'],
  '2024-01-28'::timestamptz
),
(
  'bb-004'::uuid,
  'BB-04 City Lights',
  'A dynamic oil painting of the city skyline at dusk, with warm lights beginning to twinkle across the urban landscape.',
  3100,
  'oil',
  'Urban',
  'Impressionist',
  '{"width": 60, "height": 40, "unit": "cm"}',
  ARRAY['https://images.pexels.com/photos/1519088/pexels-photo-1519088.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
  true,
  1,
  true,
  ARRAY['city', 'lights', 'urban', 'dusk'],
  '2024-02-05'::timestamptz
),
(
  'bb-005'::uuid,
  'BB-05 Floral Harmony',
  'A delicate fabric painting featuring hand-embroidered flowers in soft pastels, perfect for any living space.',
  1580,
  'fabric',
  'Floral',
  'Traditional',
  '{"width": 30, "height": 35, "unit": "cm"}',
  ARRAY['https://images.pexels.com/photos/1266808/pexels-photo-1266808.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
  true,
  2,
  false,
  ARRAY['floral', 'embroidery', 'pastels', 'delicate'],
  '2024-01-20'::timestamptz
),
(
  'bb-006'::uuid,
  'BB-06 Mountain Majesty',
  'A powerful oil painting capturing the grandeur of snow-capped mountains with dramatic lighting and rich textures.',
  3680,
  'oil',
  'Landscape',
  'Realistic',
  '{"width": 70, "height": 50, "unit": "cm"}',
  ARRAY['https://images.pexels.com/photos/1261728/pexels-photo-1261728.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
  true,
  1,
  true,
  ARRAY['mountains', 'snow', 'landscape', 'dramatic'],
  '2024-02-12'::timestamptz
),
(
  'bb-007'::uuid,
  'BB-07 Brass Ganesha Sculpture',
  'Exquisitely handcrafted brass sculpture of Lord Ganesha with intricate detailing and traditional finish. Perfect for home decoration and spiritual spaces.',
  2250,
  'handcraft',
  'Sculpture',
  'Traditional',
  '{"width": 15, "height": 20, "unit": "cm"}',
  ARRAY['https://images.pexels.com/photos/8828598/pexels-photo-8828598.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
  true,
  3,
  true,
  ARRAY['brass', 'ganesha', 'sculpture', 'spiritual', 'traditional'],
  '2024-02-15'::timestamptz
),
(
  'bb-008'::uuid,
  'BB-08 Wooden Elephant Carving',
  'Beautiful hand-carved wooden elephant with intricate patterns and smooth finish. A symbol of wisdom and good fortune.',
  1680,
  'handcraft',
  'Wood Carving',
  'Traditional',
  '{"width": 25, "height": 18, "unit": "cm"}',
  ARRAY['https://images.pexels.com/photos/6069112/pexels-photo-6069112.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
  false,
  0,
  false,
  ARRAY['wood', 'elephant', 'carving', 'handmade', 'decorative'],
  '2024-02-18'::timestamptz
),
(
  'bb-009'::uuid,
  'BB-09 Ceramic Decorative Vase',
  'Hand-painted ceramic vase with traditional Indian motifs and vibrant colors. Perfect for displaying flowers or as standalone decor.',
  1350,
  'handcraft',
  'Ceramics',
  'Traditional',
  '{"width": 12, "height": 25, "unit": "cm"}',
  ARRAY['https://images.pexels.com/photos/1669799/pexels-photo-1669799.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
  true,
  4,
  false,
  ARRAY['ceramic', 'vase', 'decorative', 'painted', 'traditional'],
  '2024-02-20'::timestamptz
),
(
  'bb-010'::uuid,
  'BB-10 Handwoven Jute Wall Hanging',
  'Eco-friendly jute wall hanging with macrame design and natural fibers. Adds rustic charm to any space.',
  980,
  'handcraft',
  'Textile Art',
  'Contemporary',
  '{"width": 30, "height": 40, "unit": "cm"}',
  ARRAY['https://images.pexels.com/photos/6207842/pexels-photo-6207842.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
  true,
  5,
  true,
  ARRAY['jute', 'macrame', 'wall hanging', 'eco-friendly', 'rustic'],
  '2024-02-22'::timestamptz
),
(
  'bb-011'::uuid,
  'BB-11 Copper Wind Chimes',
  'Melodious copper wind chimes with traditional Indian bells. Creates soothing sounds and positive energy in your space.',
  1150,
  'handcraft',
  'Decorative',
  'Traditional',
  '{"width": 8, "height": 35, "unit": "cm"}',
  ARRAY['https://images.pexels.com/photos/7319070/pexels-photo-7319070.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
  true,
  6,
  false,
  ARRAY['copper', 'wind chimes', 'bells', 'melodious', 'traditional'],
  '2024-02-25'::timestamptz
),
(
  'bb-012'::uuid,
  'BB-12 Marble Inlay Jewelry Box',
  'Exquisite marble jewelry box with traditional Pietra Dura inlay work. Features intricate floral patterns and velvet interior.',
  3250,
  'handcraft',
  'Marble Work',
  'Traditional',
  '{"width": 20, "height": 8, "unit": "cm"}',
  ARRAY['https://images.pexels.com/photos/8828598/pexels-photo-8828598.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2'],
  true,
  2,
  true,
  ARRAY['marble', 'inlay', 'jewelry box', 'pietra dura', 'luxury'],
  '2024-02-28'::timestamptz
);